import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Game Of Thrones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/got-favicon.png" />
      </Head>


    </div>
  )
}

